apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: Deployment
metadata:
  labels:
    app: dev-environment
    developer: adamschnaider
  name: text-embedding-ada-002
spec:
  forProvider:
    cognitiveAccountIdSelector:
      matchLabels:
        app: dev-environment
        developer: adamschnaider
    model:
    - format: OpenAI
      name: text-embedding-ada-002
      version: "2"
    scale:
    - type: Standard

---

apiVersion: cognitiveservices.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: orro-oai-12
  labels:
    app: dev-environment
    developer: adamschnaider
spec:
  forProvider:
    kind: OpenAI
    location: West Europe
    resourceGroupName: crossplane-lab
    skuName: S0