apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    app: dev-environment
  name: crspln-orro-aks
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        upgradeSettings:
          - maxSurge: 10%
        vmSize: Standard_DS2_v2
    dnsPrefix: crspln-orro-aks
    identity:
      - type: SystemAssigned
    location: North Europe
    resourceGroupName: crossplane-lab