apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <html>
    <head><title>Welcome</title></head>
    <body>
    <h1>Welcome Developers</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-sample-app
  template:
    metadata:
      labels:
        app: public-sample-app
    spec:
      containers:
      - name: public-sample-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: public-sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: public-sample-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
