apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        configmap.reloader.stakater.com/reload: "frontend"
    spec:
      containers:
      - name: sample-app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        volumeMounts:
        - name: frontend
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend
        configMap:
          name: frontend