apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-dev-environment
spec:
  # This Composition configures resources for the DevEnvironment XRD.
  compositeTypeRef:
    apiVersion: dev.azure.upbound.io/v1alpha1
    kind: DevEnvironment

  resources:

    # ------------------------------------------------------------------------------
    # 1) Resource Group
    # ------------------------------------------------------------------------------
    - name: resource-group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        metadata:
          name: ""
          labels:
            issue-id: ""
        spec:
          deletionPolicy: Delete
          forProvider:
            location: ""
            tags:
              provisioner: crossplane
              developer: ""
              issue-id: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.developer"
          toFieldPath: "spec.forProvider.tags[developer]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "spec.forProvider.tags[issue-id]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "metadata.name"

    # ------------------------------------------------------------------------------
    # 2) Virtual Network
    # ------------------------------------------------------------------------------
    - name: virtual-network
      base:
        apiVersion: network.azure.upbound.io/v1beta2
        kind: VirtualNetwork
        metadata:
          name: ""
          labels:
            issue-id: ""
        spec:
          forProvider:
            addressSpace:
              - 10.1.0.0/16
            location: ""
            resourceGroupName: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 3) Storage Account
    # ------------------------------------------------------------------------------
    - name: storage-account
      base:
        apiVersion: storage.azure.upbound.io/v1beta1
        kind: Account
        metadata:
          name: ""
          labels:
            issue-id: ""
        spec:
          forProvider:
            location: ""
            resourceGroupName: ""
            accountKind: StorageV2
            accountTier: Standard
            accountReplicationType: LRS
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.storageAccountName"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 4) Cognitive Services Account
    # ------------------------------------------------------------------------------
    - name: cognitive-services-account
      base:
        apiVersion: cognitiveservices.azure.upbound.io/v1beta1
        kind: Account
        metadata:
          name: ""
          labels:
            issue-id: ""
        spec:
          forProvider:
            kind: OpenAI
            location: ""
            resourceGroupName: ""
            skuName: S0
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.developer"
          toFieldPath: "metadata.labels[developer]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 5) Cognitive Services Deployment
    # ------------------------------------------------------------------------------
    - name: cognitive-services-deployment
      base:
        apiVersion: cognitiveservices.azure.upbound.io/v1beta1
        kind: Deployment
        metadata:
          name: text-embedding-ada-002
          labels:
            issue-id: ""
        spec:
          forProvider:
            cognitiveAccountIdSelector:
              matchLabels:
                issue-id: ""
            model:
              format: OpenAI
              name: text-embedding-ada-002
              version: "2"
            scale:
              - type: Standard
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "spec.forProvider.cognitiveAccountIdSelector.matchLabels.issue-id"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"
