apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-dev-environment
spec:
  compositeTypeRef:
    apiVersion: dev.azure.upbound.io/v1alpha1
    kind: DevEnvironment

  resources:

    # ------------------------------------------------------------------------------
    # 1) Resource Group
    # ------------------------------------------------------------------------------
    - name: resource-group
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        metadata:
          labels:
            issue-id: ""
        spec:
          deletionPolicy: Delete
          forProvider:
            location: ""
            tags:
              provisioner: crossplane
              developer: ""
              issue-id: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.developer"
          toFieldPath: "spec.forProvider.tags[developer]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "spec.forProvider.tags[issue-id]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "metadata.name"

    # ------------------------------------------------------------------------------
    # 2) Virtual Network
    # ------------------------------------------------------------------------------
    - name: virtual-network
      base:
        apiVersion: network.azure.upbound.io/v1beta2
        kind: VirtualNetwork
        metadata:
          labels:
            issue-id: ""
        spec:
          forProvider:
            addressSpace:
              - 10.1.0.0/16
            location: ""
            resourceGroupName: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 3) Storage Account
    # ------------------------------------------------------------------------------
    - name: storage-account
      base:
        apiVersion: storage.azure.upbound.io/v1beta1
        kind: Account
        metadata:
          labels:
            issue-id: ""
        spec:
          forProvider:
            location: ""
            resourceGroupName: ""
            accountKind: StorageV2
            accountTier: Standard
            accountReplicationType: LRS
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.storageAccountName"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 4) Cognitive Services Account
    # ------------------------------------------------------------------------------
    - name: cognitive-services-account
      base:
        apiVersion: cognitiveservices.azure.upbound.io/v1beta1
        kind: Account
        metadata:
          labels:
            issue-id: ""
        spec:
          forProvider:
            kind: OpenAI
            location: ""
            resourceGroupName: ""
            skuName: S0
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.oaiResourceName"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.developer"
          toFieldPath: "metadata.labels[developer]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"

    # ------------------------------------------------------------------------------
    # 5) Cognitive Services Deployment
    # ------------------------------------------------------------------------------
    - name: cognitive-services-deployment
      base:
        apiVersion: cognitiveservices.azure.upbound.io/v1beta1
        kind: Deployment
        metadata:
          labels:
            issue-id: ""
        spec:
          forProvider:
            cognitiveAccountIdSelector:
              matchLabels:
                issue-id: ""
            model:
              - format: OpenAI
                name: ""
                version: "2"
            scale:
              - type: Standard
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "spec.forProvider.cognitiveAccountIdSelector.matchLabels.issue-id"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.oaiModelName"
              - fromFieldPath: "spec.parameters.issueId"
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.oaiModelName"
          toFieldPath: "spec.forProvider.model[0].name"

    # ------------------------------------------------------------------------------
    # 6) Kubernetes Cluster
    # ------------------------------------------------------------------------------
    - name: kubernetes-cluster
      base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster
        metadata:
          labels:
            issue-id: ""
        spec:
          forProvider:
            defaultNodePool:
              - name: default
                nodeCount: 1
                upgradeSettings:
                  - maxSurge: "10%"
                vmSize: Standard_D2_v2
            dnsPrefix: ""
            identity:
              - type: SystemAssigned
            location: ""
            resourceGroupName: ""
          deletionPolicy: Delete
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.issueId"
          toFieldPath: "metadata.labels[issue-id]"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.resourceGroup"
          toFieldPath: "spec.forProvider.resourceGroupName"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.aksName"
          toFieldPath: "spec.forProvider.dnsPrefix"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.aksName"
          toFieldPath: "metadata.name"