apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-dev-environment
  labels:
    purpose: dev-environment
spec:
  compositeTypeRef:
    apiVersion: dev.azure.upbound.io/v1alpha1
    kind: DevEnvironment
  resources:
    - name: virtual-network
      base:
        apiVersion: network.azure.upbound.io/v1beta1
        kind: VirtualNetwork
        metadata:
          name: "{{ .parameters.virtualNetworkName }}"
        spec:
          forProvider:
            addressSpace:
              - 10.0.0.0/16
            location: "{{ .parameters.region }}"
            resourceGroupName: "{{ .parameters.resourceGroup }}"