apiVersion: dev.azure.upbound.io/v1alpha1
kind: DevEnvironment
metadata:
  name: dev-env-adamschnaider-42
spec:
  parameters:
    region: southeastasia
    resourceGroup: env-adamschnaider-42-rg
    developer: adamschnaider
    issueId: "42"
    storageAccountName: ufxegzsk7uizr7nz