apiVersion: dev.azure.upbound.io/v1alpha1
kind: DevEnvironment
metadata:
  name: dev-env-adamschnaider-78
spec:
  parameters:
    region: eastus
    resourceGroup: rg-adamschnaider-78
    developer: adamschnaider
    issueId: "78"
    storageAccountName: 0f2w7cp76j58zgev
    oaiModelName: "text-embedding-ada-002"
    oaiResourceName: "oai-adamschnaider-78"
    aksName: "aks-adamschnaider-78"