apiVersion: dev.azure.upbound.io/v1alpha1
kind: DevEnvironment
metadata:
  name: dev-env-adamschnaider-63
spec:
  parameters:
    region: australiaeast
    resourceGroup: rg-adamschnaider-63
    developer: adamschnaider
    issueId: "63"
    storageAccountName: v3pzahl0zcwa6gfg
    oaiModelName: "text-embedding-ada-002"
    oaiResourceName: "oai-adamschnaider-63"
    aksName: "aks-adamschnaider-63"