apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: azure-virtual-network
spec:
  forProvider:
    addressSpace:
      - 10.1.0.0/16
    location: "Sweden Central"
    resourceGroupName: crossplane-lab