apiVersion: dev.azure.upbound.io/v1alpha1
kind: DevEnvironment
metadata:
  name: dev-env-adamschnaider-93
spec:
  parameters:
    region: eastus
    resourceGroup: rg-adamschnaider-93
    developer: adamschnaider
    issueId: "93"
    storageAccountName: vn1a7d7u21w2nvck
    oaiModelName: "text-embedding-ada-002"
    oaiResourceName: "oai-adamschnaider-93"
    aksName: "aks-adamschnaider-93"