name: Provision Environment on Issue Open via ArgoCD Crossplane
run-name: Provision or Update Dev Env on Issue ${{ github.event.issue.number }} for ${{ github.actor }}

on:
  workflow_call:
    secrets:
      azure_credentials:
        required: true
    inputs:
      app_name:
        required: true
        type: string
      region:
        required: true
        type: string
      environment_type:
        required: true
        type: string
      unique_id:
        required: true
        type: string
      repository:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      run_id:
        required: true
        type: string
      crossplane_aks_cluster:
        required: false
        type: string
      crossplane_aks_cluster_rg:
        required: false
        type: string

jobs:
  provision:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      branch_name: ${{ steps.set_branch_name.outputs.branch_name }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Set branch name
        id: set_branch_name
        run: echo "branch_name=create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Create or Update DevEnvironment File
        id: create_dev_env_file
        run: |
          FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          TEMPLATE_PATH="infrastructure/azure/resources-samples/dev-env-template.yaml"
          RG_NAME="env-${{ github.actor }}-${{ github.event.issue.number }}-rg"
          STORAGE_ACCOUNT_NAME="$(echo dev${{ inputs.unique_id }}$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 16) | head -c 24)"
          
          mkdir -p infrastructure/azure/dev-envs

          export GITHUB_ACTOR=${{ github.actor }}
          export GITHUB_EVENT_ISSUE_NUMBER=${{ github.event.issue.number }}
          export REGION=${{ inputs.region }}
          export RESOURCE_GROUP=$RG_NAME
          export STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME
          envsubst < $TEMPLATE_PATH > $FILE_PATH

          echo "Final contents of $FILE_PATH:"
          cat "$FILE_PATH"

          echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Add DevEnvironment file for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          new_branch: ${{ steps.set_branch_name.outputs.branch_name }}
          push: true
          add: ${{ steps.create_dev_env_file.outputs.file_path }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.set_branch_name.outputs.branch_name }}
          base: "main"
          title: "Dev environment for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          body: |
            This PR adds a new or updated DevEnvironment file for #${{ github.event.issue.number }}.
            Once merged, ArgoCD will deploy or update the environment.
          draft: false