name: Provision Environment on Issue Open via ArgoCD Crossplane
run-name: Provision or Update Dev Env on Issue ${{ github.event.issue.number }} for ${{ github.actor }}

on:
  workflow_call:
    secrets:
      azure_credentials:
        required: true
    inputs:
      app_name:
        required: true
        type: string
      region:
        required: true
        type: string
      environment_type:
        required: true
        type: string
      unique_id:
        required: true
        type: string
      repository:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      run_id:
        required: true
        type: string
      crossplane_aks_cluster:
        required: false
        type: string
      crossplane_aks_cluster_rg:
        required: false
        type: string

jobs:
  provision:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          fetch-depth: 0   # Avoid shallow clones that can cause "no-diff" confusion

      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - id: create_or_update_file
        name: Create or Update DevEnvironment File
        run: |
          FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          RG_NAME="env-${{ github.actor }}-${{ github.event.issue.number }}-rg"
          
          # We'll inject a forced-diff line (timestamp or run_id comment).
          FORCE_DIFF="# Force update: ${{ github.run_id }} at $(date +%s)"

          mkdir -p infrastructure/azure/dev-envs

          if [ -f "$FILE_PATH" ]; then
            echo "File already exists, we will update it with a forced-diff line."
            # Append or modify a comment line so there's guaranteed to be a new diff
            # We can do it simply by adding a comment line at the end:
            echo "$FORCE_DIFF" >> "$FILE_PATH"
          else
            echo "File does not exist, creating a new one."
            cat <<EOF > "$FILE_PATH"
              apiVersion: dev.azure.upbound.io/v1alpha1
              kind: DevEnvironment
              metadata:
                name: dev-env-${{ github.actor }}-${{ github.event.issue.number }}
                labels:
                  developer: "${{ github.actor }}"
                  issue-id: "${{ github.event.issue.number }}"
              spec:
                parameters:
                  region: eastus
                  resourceGroup: "$RG_NAME"
                  developer: "${{ github.actor }}"
                  issueId: "${{ github.event.issue.number }}"
                  # Keep under 24 chars for Azure
                  storageAccountName: "$(echo dev${{ inputs.unique_id }}$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 16) | head -c 24)"
              $FORCE_DIFF
              EOF
          fi

          # Print final file for debugging
          echo "Final contents:"
          cat "$FILE_PATH"

      - name: Create new branch
        run: |
          BRANCH_NAME="create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          git checkout -b "$BRANCH_NAME"

      - name: Commit changes
        run: |
          FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          git add "$FILE_PATH"
          git commit -m "Dev environment for ${{ github.actor }} issue #${{ github.event.issue.number }} - forced update"

      - name: Push changes
        run: |
          BRANCH_NAME="create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          base: "main"
          title: "Dev environment for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          body: |
            A new or updated DevEnvironment file for #${{ github.event.issue.number }} has been committed.
            Merging this PR will have ArgoCD pick it up and deploy (or update) the environment.
          draft: false