name: Provision Environment on Issue Open via ArgoCD Crossplane
run-name: Provision or Update Dev Env on Issue ${{ github.event.issue.number }} for ${{ github.actor }}

on:
  workflow_call:
    secrets:
      azure_credentials:
        required: true
    inputs:
      app_name:
        required: true
        type: string
      region:
        required: true
        type: string
      environment_type:
        required: true
        type: string
      unique_id:
        required: true
        type: string
      repository:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      run_id:
        required: true
        type: string
      crossplane_aks_cluster:
        required: false
        type: string
      crossplane_aks_cluster_rg:
        required: false
        type: string

jobs:
  provision:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      branch_name: ${{ steps.set_branch_name.outputs.branch_name }}

    steps:
      # Step 1: Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          fetch-depth: 0

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      # Step 3: Set branch name dynamically
      - name: Set branch name
        id: set_branch_name
        run: echo "branch_name=create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      # Step 4: Create and switch to a new branch
      - name: Create and switch to a new branch
        run: |
          git checkout -b ${{ steps.set_branch_name.outputs.branch_name }}

      # Step 5: Create or update the DevEnvironment file
      - name: Create or Update DevEnvironment File
        id: create_dev_env_file
        run: |
          # Set file paths and environment variables
          export FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          export TEMPLATE_PATH="infrastructure/azure/resources-samples/dev-env-template.yaml"
          export REGION="${{ inputs.region }}"
          export RESOURCE_GROUP="env-${{ github.actor }}-${{ github.event.issue.number }}-rg"
          export STORAGE_ACCOUNT_NAME="$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 16)"
          
          # Create the directory and the file
          mkdir -p $(dirname "$FILE_PATH")
          envsubst < $TEMPLATE_PATH > $FILE_PATH

          # Debugging output
          echo "Created file at: $FILE_PATH"
          cat $FILE_PATH

      # Step 6: Debug before committing
      - name: Debug Verify Git Status Before Commit
        run: |
          echo "Checking Git status before commit..."
          git status
          echo "Listing directory contents:"
          ls -la infrastructure/azure/dev-envs/

      # Step 7: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git add infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml
          git status
          git commit -m "Add DevEnvironment file for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          git push --set-upstream origin ${{ steps.set_branch_name.outputs.branch_name }}

      # Step 8: Debug the remote branch state
      - name: Verify Remote Branch After Push
        run: |
          echo "Verifying the remote branch state..."
          git ls-remote origin | grep ${{ steps.set_branch_name.outputs.branch_name }}
          git log origin/${{ steps.set_branch_name.outputs.branch_name }} --oneline

      # Step 9: Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.set_branch_name.outputs.branch_name }}
          base: main
          title: "Dev environment for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          body: |
            This PR adds a new or updated DevEnvironment file for #${{ github.event.issue.number }}.
            Once merged, ArgoCD will deploy or update the environment.
          draft: false
