name: Provision Environment on Issue Open via ArgoCD Crossplane
run-name: Provision or Update Dev Env on Issue ${{ github.event.issue.number }} for ${{ github.actor }}

on:
  workflow_call:
    secrets:
      azure_credentials:
        required: true
    inputs:
      app_name:
        required: true
        type: string
      region:
        required: true
        type: string
      environment_type:
        required: true
        type: string
      unique_id:
        required: true
        type: string
      repository:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      run_id:
        required: true
        type: string
      crossplane_aks_cluster:
        required: false
        type: string
      crossplane_aks_cluster_rg:
        required: false
        type: string

jobs:
  provision:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: main
          fetch-depth: 0   # Avoid shallow clones that can cause "no-diff" confusion

      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Create or Update DevEnvironment File
        run: |
          FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          TEMPLATE_PATH="infrastructure/azure/resources-samples/dev-env-temaplate.yaml"
          RG_NAME="env-${{ github.actor }}-${{ github.event.issue.number }}-rg"
          STORAGE_ACCOUNT_NAME="$(echo dev${{ inputs.unique_id }}$(LC_ALL=C tr -dc 'a-z0-9' < /dev/urandom | head -c 16) | head -c 24)"
          
          mkdir -p infrastructure/azure/dev-envs

          # Export environment variables for envsubst
          export GITHUB_ACTOR=${{ github.actor }}
          export GITHUB_EVENT_ISSUE_NUMBER=${{ github.event.issue.number }}
          export REGION=${{ inputs.region }}
          export RESOURCE_GROUP=$RG_NAME
          export STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME
          envsubst < $TEMPLATE_PATH > $FILE_PATH

          # Print final file for debugging
          echo "Final contents:"
          cat "$FILE_PATH"

      - name: Create new branch
        run: |
          BRANCH_NAME="create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          git checkout -b "$BRANCH_NAME"

      - name: Commit changes
        run: |
          FILE_PATH="infrastructure/azure/dev-envs/dev-env-${{ github.actor }}-${{ github.event.issue.number }}.yaml"
          git add "$FILE_PATH"
          git commit -m "Dev environment for ${{ github.actor }} issue #${{ github.event.issue.number }} - forced update"

      - name: Push changes
        run: |
          BRANCH_NAME="create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "create-dev-env-${{ github.actor }}-${{ github.event.issue.number }}"
          base: "main"
          title: "Dev environment for ${{ github.actor }} (Issue #${{ github.event.issue.number }})"
          body: |
            A new or updated DevEnvironment file for #${{ github.event.issue.number }} has been committed.
            Merging this PR will have ArgoCD pick it up and deploy (or update) the environment.
          draft: false